import os
import subprocess
import tempfile
import time
from typing import Tuple, Dict, Any

class Executor:
    """
    Executes Python scripts generated by the Hacker in a controlled environment.
    Captures stdout, stderr, and execution time to provide rich evidence for the Historian.
    """
    def __init__(self, sandbox_dir: str = "sandbox"):
        self.sandbox_dir = sandbox_dir
        if not os.path.exists(self.sandbox_dir):
            os.makedirs(self.sandbox_dir)

    def execute_python_code(self, code: str, run_id: str, timeout_seconds: int = 30) -> Dict[str, Any]:
        """
        Writes the code to a temporary file and executes it via subprocess.
        Returns a dictionary containing the execution trace.
        """
        # Create a unique filename and artifact directory for this execution
        filename = f"exploit_{run_id}.py"
        filepath = os.path.join(self.sandbox_dir, filename)
        artifact_dir = os.path.join(self.sandbox_dir, f"artifacts_{run_id}")
        
        if not os.path.exists(artifact_dir):
            os.makedirs(artifact_dir)

        # Write the code to the sandbox
        with open(filepath, "w") as f:
            f.write(code)

        evidence = {
            "execution_file": filepath,
            "artifact_dir": artifact_dir,
            "stdout": "",
            "stderr": "",
            "return_code": None,
            "timeout_triggered": False,
            "execution_time_ms": 0
        }

        # Setup environment variables for the payload script
        env = os.environ.copy()
        env["RUN_ID"] = run_id
        env["ARTIFACT_DIR"] = os.path.abspath(artifact_dir)

        start_time = time.time()
        try:
            # Run the script. In a real red-team scenario, you might use a Docker container 
            # or a stricter sandbox. Here we just use subprocess for local testing.
            process = subprocess.run(
                ["python", filepath],
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
                env=env
            )
            
            evidence["stdout"] = process.stdout
            evidence["stderr"] = process.stderr
            evidence["return_code"] = process.returncode
            
        except subprocess.TimeoutExpired as e:
            evidence["stdout"] = e.stdout.decode('utf-8') if e.stdout else ""
            evidence["stderr"] = e.stderr.decode('utf-8') if e.stderr else ""
            evidence["timeout_triggered"] = True
            evidence["return_code"] = -1
        except Exception as e:
            evidence["stderr"] = str(e)
            evidence["return_code"] = -2
            
        end_time = time.time()
        evidence["execution_time_ms"] = int((end_time - start_time) * 1000)
        
        return evidence

    def clean_sandbox(self):
        """Optional: cleans up old execution scripts."""
        for f in os.listdir(self.sandbox_dir):
            if f.endswith(".py"):
                os.remove(os.path.join(self.sandbox_dir, f))
